In [0]:
%config InlineBackend.figure_formats = ['svg']
from random import sample
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d
from numpy import linalg as LA

In [0]:
M = np.matrix([[2, 1], [1, 1]])
evals, evecs = LA.eig(M)
print('eigenvalues:',evals)
print('corresponding eigenvectors are the columns:')
print(evecs)

eigenvalues: [2.61803399 0.38196601]
corresponding eigenvectors are the columns:
[[ 0.85065081 -0.52573111]
 [ 0.52573111  0.85065081]]


In [0]:
# PART 2 - Eigenvalues 

# Transition Matrix 
S = np.matrix([
     #    v1     v2      v3      v4       v5
    [     0,  (1/3),  (1/3),  (1/3),      0], # v1
    [ (1/3),      0,  (1/3),      0,  (1/3)], # v2
    [ (1/3),  (1/3),      0,  (1/3),      0], # v3
    [ (1/2),      0,  (1/2),      0,      0], # v4
    [     0,      1,      0,      0,      0], # v1

])

evals, evecs = LA.eig(S.T)
print('eigenvalues:',evals)
print('corresponding eigenvectors are the columns:')
print( np.round(np.real(evecs),6))


eigenvalues: [ 1.        +0.00000000e+00j  0.43425855+0.00000000e+00j
 -0.76759188+0.00000000e+00j -0.33333333+6.79869978e-17j
 -0.33333333-6.79869978e-17j]
corresponding eigenvectors are the columns:
[[ 0.53033   0.305515 -0.364938 -0.301477 -0.301477]
 [ 0.53033  -0.61103   0.729876  0.177421  0.177421]
 [ 0.53033   0.305515 -0.364938  0.656318  0.656318]
 [ 0.353553  0.469022  0.316955 -0.354842 -0.354842]
 [ 0.176777 -0.469022 -0.316955 -0.177421 -0.177421]]


In [0]:
# PART 2 - Power Method 
import cvxpy as cp

S = np.matrix([
     #    v1     v2      v3      v4       v5
    [     0,  (1/3),  (1/3),  (1/3),      0], # v1
    [ (1/3),      0,  (1/3),      0,  (1/3)], # v2
    [ (1/3),  (1/3),      0,  (1/3),      0], # v3
    [ (1/2),      0,  (1/2),      0,      0], # v4
    [     0,      1,      0,      0,      0], # v5

])

# def iterate():
#     n = 0
#     x = np.matrix([
#                  [0],
#                  [0], 
#                  [0],
#                  [0],
#                  [1]
#                  ])
#     while n < 100:
#       n+= 1
#       a = S.T**n@x
#       b = S.T**(n+1)@x
#       if np.allclose(a,b):
#         print('iteration: ', n)
#         print(a)
#         print(' ')
#         break;

def iterate(P, v):
    converge = 0
    while converge < 301:
      init = v
      v = P.T @ init
      converge += 1
      print('n: ', converge)
      if (np.allclose(init,v)):
        print('iteration: ', converge)
        return v




v = np.matrix([
                 [0],
                 [0], 
                 [0],
                 [0],
                 [1]
                 ])
iterate(S,v )


# v1 = 47
# v2 = 49 
# v3 = 47 
# v4 = 48 
# v5 = 50 



n:  1
n:  2
n:  3
n:  4
n:  5
n:  6
n:  7
n:  8
n:  9
n:  10
n:  11
n:  12
n:  13
n:  14
n:  15
n:  16
n:  17
n:  18
n:  19
n:  20
n:  21
n:  22
n:  23
n:  24
n:  25
n:  26
n:  27
n:  28
n:  29
n:  30
n:  31
n:  32
n:  33
n:  34
n:  35
n:  36
n:  37
n:  38
n:  39
n:  40
n:  41
n:  42
n:  43
n:  44
n:  45
n:  46
n:  47
n:  48
n:  49
n:  50
n:  51
iteration:  51


matrix([[0.24999962],
        [0.25000077],
        [0.24999962],
        [0.166667  ],
        [0.083333  ]])

In [0]:
# PART 3 - directed graph 
import cvxpy as cp

S = np.matrix([
     #    v1     v2      v3      v4       v5
    [     0,  (1/3),  (1/3),  (1/3),      0], # v1
    [     0,      0,      0,      0,      1], # v2
    [     0,      1,      0,      0,      0], # v3
    [     0,      0,      1,      0,      0], # v4
    [ (1/5),  (1/5),  (1/5),  (1/5),  (1/5)]  # v5

])

N = np.matrix([
     #    v1     v2      v3      v4       v5
    [ (1/5),  (1/5),  (1/5),  (1/5),  (1/5)], # v1
    [ (1/5),  (1/5),  (1/5),  (1/5),  (1/5)], # v2
    [ (1/5),  (1/5),  (1/5),  (1/5),  (1/5)], # v3
    [ (1/5),  (1/5),  (1/5),  (1/5),  (1/5)], # v4
    [ (1/5),  (1/5),  (1/5),  (1/5),  (1/5)]  # v5

])

prob = 1

# New Transition Vector 
P = (prob * N) + ( (1 - prob) * S)

print(P)
print('')


# def iterate(P):
#     n = 0
#     x = np.matrix([
#                  [1],
#                  [0], 
#                  [0],
#                  [0],
#                  [0]
#                  ])
#     while n < 100:
#       n+= 1
#       a = P.T**n@x
#       b = P.T**(n+1)@x
#       if np.allclose(a,b):
#         print('iteration: ', n)
#         print(a)
#         print(' ')
#         break;



def iterate(P, v):
    converge = 0
    while converge < 301:
      print('n: ', converge)
      print(v)
      init = v
      v = P.T @ init
      converge += 1
      if (np.allclose(init,v)):
        print('n: ', converge)
        print(v)
        return v



v = np.matrix([
                 [1],
                 [0], 
                 [0],
                 [0],
                 [0]
                 ])
iterate(P,v)

#eigenvalues 
evals, evecs = LA.eig(P.T)
print('eigenvalues:',evals)
print('corresponding eigenvectors are the columns:')
print( np.round(np.real(evecs),6))



[[0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2]]

n:  0
[[1]
 [0]
 [0]
 [0]
 [0]]
n:  1
[[0.2]
 [0.2]
 [0.2]
 [0.2]
 [0.2]]
n:  2
[[0.2]
 [0.2]
 [0.2]
 [0.2]
 [0.2]]
eigenvalues: [ 0.00000000e+00+0.00000000e+00j  1.00000000e+00+0.00000000e+00j
  1.38777878e-17+0.00000000e+00j -1.01025814e-33+1.16738655e-33j
 -1.01025814e-33-1.16738655e-33j]
corresponding eigenvectors are the columns:
[[-0.894427  0.447214 -0.223607  0.672436  0.672436]
 [ 0.223607  0.447214 -0.223607 -0.168109 -0.168109]
 [ 0.223607  0.447214 -0.223607  0.261108  0.261108]
 [ 0.223607  0.447214 -0.223607 -0.591631 -0.591631]
 [ 0.223607  0.447214  0.894427 -0.173805 -0.173805]]
